### ISSUE TITLE
OSError: [errorno 8] Exec format error: 'HCopy'

### ISSUE THREAD

**Issue by iggy12345** [maxrmorrison/pyfoal#13]
When trying to use `pyfoal.from_files_to_files(text_files, audio_files, output_files)` I get the following exception

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 95, in from_file_to_file
    from_file(text_file, audio_file).save(output_file)
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 80, in from_file
    return align(text, audio, SAMPLE_RATE)
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 56, in align
    return align.aligner(text, audio, duration)
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 143, in __call__
    self.format(directory, audio, script_file)
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 200, in format
    subprocess.Popen(
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'HCopy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/site-packages/pyfoal/core.py", line 111, in from_files_to_files
    pool.starmap(align_fn, zip(text_files, audio_files, output_files))
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/aaron/anaconda3/envs/ling120-final/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: [Errno 8] Exec format error: 'HCopy'
```

I can run the program without multiprocessing and it works fine, but when I use multiprocessing with pyfoal I get this exception.

**Comment by maxrmorrison** [comment]
What version of HTK did you install?

**Comment by iggy12345** [comment]
I installed 3.4.0, just like requested. I did a little more investigating, and found that this is only true for when I run it on WSL and not native linux.

**Comment by maxrmorrison** [comment]
Thanks for following up. That's good to know. Given that this is a HTK + WSL compatibility issue I will go ahead and close the issue.
