### ISSUE TITLE
Multiprocessing issue

### ISSUE THREAD

**Issue by pranavmalikk** [maxrmorrison/pyfoal#8]
I tried running the `pyfoal.from_files_to_files` method to get my alignments. But due to some multiprocessor issue i'm not able to execute the method. My current structure is the following:

```
json_path = sorted([os.path.abspath(files) for files in glob.glob(os.path.join(directory, f'**/*{ext1}'), recursive= True)])
wav_path = sorted([os.path.abspath(files) for files in glob.glob(os.path.join(directory, f'**/*{ext2}'), recursive= True)])
directory_path = sorted([os.path.join(os.path.dirname(files), "alignment.json") for files in json_path])

pyfoal.from_files_to_files(json_path, wav_path, directory_path).
```

Where json_path is the array of all json paths, wav_path is the array of all wav paths, and directory_path is the array of the location where I want the pyfoal to be placed in. I get the following error when trying to run the code:

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**The full stacktrace is below:**
  File "<string>", line 1, in <module>
rozen to produce an executable.
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    prepare(preparation_data)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 457, in <module>
    _run_code(code, mod_globals, init_globals,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    create_alignment_json(colab_files, ext1 = '.wav', ext2 = '.json')
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 388, in create_alignment_json
    exec(code, run_globals)
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 457, in <module>
    pyfoal.from_files_to_files(json_path, wav_path, directory_path)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/site-packages/pyfoal/core.py", line 109, in from_files_to_files
    with mp.get_context('spawn').Pool() as pool:
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    create_alignment_json(colab_files, ext1 = '.wav', ext2 = '.json')
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 388, in create_alignment_json
    pyfoal.from_files_to_files(json_path, wav_path, directory_path)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/site-packages/pyfoal/core.py", line 109, in from_files_to_files
    with mp.get_context('spawn').Pool() as pool:
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    self._popen = self._Popen(self)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    return Popen(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    w.start()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    self._launch(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    return Popen(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    _check_not_importing_main()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._launch(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 457, in <module>
    create_alignment_json(colab_files, ext1 = '.wav', ext2 = '.json')
  File "/Users/pranavmalik/Documents/Clipper Dataset/scripts/audio_preprocess.py", line 388, in create_alignment_json
    pyfoal.from_files_to_files(json_path, wav_path, directory_path)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/site-packages/pyfoal/core.py", line 109, in from_files_to_files
    with mp.get_context('spawn').Pool() as pool:
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/pranavmalik/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

And it just repeats over and over

**Comment by maxrmorrison** [comment]
I think you need to put your code inside the main module
```
if __name == '__main__':
    # Your code
```

**Comment by pranavmalikk** [comment]
Works thank you!
